"""create core schema

Revision ID: 926a6602cc5c
Revises: 
Create Date: 2026-04-18 15:43:10.482080
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '926a6602cc5c'
down_revision = None
branch_labels = None
depends_on = None

conversation_type = postgresql.ENUM("room", "dm", name="conversation_type", create_type=False)
friend_request_status = postgresql.ENUM(
    "pending",
    "accepted",
    "rejected",
    "cancelled",
    name="friend_request_status",
    create_type=False,
)
dm_status = postgresql.ENUM("active", "frozen", name="dm_status", create_type=False)
room_visibility = postgresql.ENUM("public", "private", name="room_visibility", create_type=False)
invitation_status = postgresql.ENUM(
    "pending",
    "accepted",
    "declined",
    "revoked",
    name="invitation_status",
    create_type=False,
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    conversation_type.create(bind, checkfirst=True)
    friend_request_status.create(bind, checkfirst=True)
    dm_status.create(bind, checkfirst=True)
    room_visibility.create(bind, checkfirst=True)
    invitation_status.create(bind, checkfirst=True)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploader_user_id', sa.Uuid(), nullable=True),
    sa.Column('comment_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_storage_key'), 'attachments', ['storage_key'], unique=True)
    op.create_index(op.f('ix_attachments_uploader_user_id'), 'attachments', ['uploader_user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', conversation_type, nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('message_sequence_head', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_type'), 'conversations', ['type'], unique=False)
    op.create_table('friend_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requester_user_id', sa.Uuid(), nullable=False),
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', friend_request_status, nullable=False),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requester_user_id <> recipient_user_id', name='ck_friend_requests_distinct_users'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_user_id', 'recipient_user_id', name='uq_friend_requests_requester_recipient')
    )
    op.create_index(op.f('ix_friend_requests_recipient_user_id'), 'friend_requests', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_friend_requests_requester_user_id'), 'friend_requests', ['requester_user_id'], unique=False)
    op.create_table('friendships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_one_id', sa.Uuid(), nullable=False),
    sa.Column('user_two_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_one_id <> user_two_id', name='ck_friendships_distinct_users'),
    sa.ForeignKeyConstraint(['user_one_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_two_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_one_id', 'user_two_id', name='uq_friendships_user_pair')
    )
    op.create_index('ix_friendships_user_one_id', 'friendships', ['user_one_id'], unique=False)
    op.create_index('ix_friendships_user_two_id', 'friendships', ['user_two_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('user_blocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('blocker_user_id', sa.Uuid(), nullable=False),
    sa.Column('blocked_user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blocker_user_id <> blocked_user_id', name='ck_user_blocks_distinct_users'),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_user_id', 'blocked_user_id', name='uq_user_blocks_blocker_blocked')
    )
    op.create_index(op.f('ix_user_blocks_blocked_user_id'), 'user_blocks', ['blocked_user_id'], unique=False)
    op.create_index(op.f('ix_user_blocks_blocker_user_id'), 'user_blocks', ['blocker_user_id'], unique=False)
    op.create_table('user_credentials',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_session_token_hash'), 'user_sessions', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('conversation_members',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    op.create_index('ix_conversation_members_user_id', 'conversation_members', ['user_id'], unique=False)
    op.create_table('dm_metadata',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_one_id', sa.Uuid(), nullable=False),
    sa.Column('user_two_id', sa.Uuid(), nullable=False),
    sa.Column('status', dm_status, nullable=False),
    sa.Column('initiated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_one_id <> user_two_id', name='ck_dm_metadata_distinct_users'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['initiated_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_one_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_two_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('user_one_id', 'user_two_id', name='uq_dm_metadata_user_pair')
    )
    op.create_index(op.f('ix_dm_metadata_user_one_id'), 'dm_metadata', ['user_one_id'], unique=False)
    op.create_index(op.f('ix_dm_metadata_user_two_id'), 'dm_metadata', ['user_two_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=True),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('reply_to_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'sequence_number', name='uq_messages_conversation_sequence')
    )
    op.create_index(op.f('ix_messages_author_user_id'), 'messages', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_id_id', 'messages', ['conversation_id', 'id'], unique=False)
    op.create_table('moderation_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moderation_events_actor_user_id'), 'moderation_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_moderation_events_conversation_id'), 'moderation_events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_moderation_events_event_type'), 'moderation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_moderation_events_target_user_id'), 'moderation_events', ['target_user_id'], unique=False)
    op.create_table('room_metadata',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visibility', room_visibility, nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index(op.f('ix_room_metadata_name'), 'room_metadata', ['name'], unique=True)
    op.create_index(op.f('ix_room_metadata_owner_user_id'), 'room_metadata', ['owner_user_id'], unique=False)
    op.create_table('security_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['user_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_events_actor_user_id'), 'security_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_session_id'), 'security_events', ['session_id'], unique=False)
    op.create_table('conversation_reads',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_read_message_id', sa.BigInteger(), nullable=True),
    sa.Column('last_read_sequence_number', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    op.create_table('message_attachments',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('attachment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'attachment_id')
    )
    op.create_table('room_admins',
    sa.Column('room_conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('granted_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_conversation_id'], ['room_metadata.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_conversation_id', 'user_id')
    )
    op.create_index('ix_room_admins_user_id', 'room_admins', ['user_id'], unique=False)
    op.create_table('room_bans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('banned_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banned_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_conversation_id'], ['room_metadata.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_conversation_id', 'user_id', name='uq_room_bans_room_user')
    )
    op.create_index(op.f('ix_room_bans_room_conversation_id'), 'room_bans', ['room_conversation_id'], unique=False)
    op.create_index(op.f('ix_room_bans_user_id'), 'room_bans', ['user_id'], unique=False)
    op.create_table('room_invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('room_conversation_id', sa.Uuid(), nullable=False),
    sa.Column('inviter_user_id', sa.Uuid(), nullable=True),
    sa.Column('invitee_user_id', sa.Uuid(), nullable=False),
    sa.Column('status', invitation_status, nullable=False),
    sa.Column('invitation_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_conversation_id'], ['room_metadata.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_conversation_id', 'invitee_user_id', name='uq_room_invitations_room_invitee')
    )
    op.create_index(op.f('ix_room_invitations_invitee_user_id'), 'room_invitations', ['invitee_user_id'], unique=False)
    op.create_index(op.f('ix_room_invitations_room_conversation_id'), 'room_invitations', ['room_conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()

    op.drop_index(op.f('ix_room_invitations_room_conversation_id'), table_name='room_invitations')
    op.drop_index(op.f('ix_room_invitations_invitee_user_id'), table_name='room_invitations')
    op.drop_table('room_invitations')
    op.drop_index(op.f('ix_room_bans_user_id'), table_name='room_bans')
    op.drop_index(op.f('ix_room_bans_room_conversation_id'), table_name='room_bans')
    op.drop_table('room_bans')
    op.drop_index('ix_room_admins_user_id', table_name='room_admins')
    op.drop_table('room_admins')
    op.drop_table('message_attachments')
    op.drop_table('conversation_reads')
    op.drop_index(op.f('ix_security_events_session_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_actor_user_id'), table_name='security_events')
    op.drop_table('security_events')
    op.drop_index(op.f('ix_room_metadata_owner_user_id'), table_name='room_metadata')
    op.drop_index(op.f('ix_room_metadata_name'), table_name='room_metadata')
    op.drop_table('room_metadata')
    op.drop_index(op.f('ix_moderation_events_target_user_id'), table_name='moderation_events')
    op.drop_index(op.f('ix_moderation_events_event_type'), table_name='moderation_events')
    op.drop_index(op.f('ix_moderation_events_conversation_id'), table_name='moderation_events')
    op.drop_index(op.f('ix_moderation_events_actor_user_id'), table_name='moderation_events')
    op.drop_table('moderation_events')
    op.drop_index('ix_messages_conversation_id_id', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_author_user_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_dm_metadata_user_two_id'), table_name='dm_metadata')
    op.drop_index(op.f('ix_dm_metadata_user_one_id'), table_name='dm_metadata')
    op.drop_table('dm_metadata')
    op.drop_index('ix_conversation_members_user_id', table_name='conversation_members')
    op.drop_table('conversation_members')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token_hash'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_table('user_credentials')
    op.drop_index(op.f('ix_user_blocks_blocker_user_id'), table_name='user_blocks')
    op.drop_index(op.f('ix_user_blocks_blocked_user_id'), table_name='user_blocks')
    op.drop_table('user_blocks')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('ix_friendships_user_two_id', table_name='friendships')
    op.drop_index('ix_friendships_user_one_id', table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_friend_requests_requester_user_id'), table_name='friend_requests')
    op.drop_index(op.f('ix_friend_requests_recipient_user_id'), table_name='friend_requests')
    op.drop_table('friend_requests')
    op.drop_index(op.f('ix_conversations_type'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_attachments_uploader_user_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_storage_key'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    invitation_status.drop(bind, checkfirst=True)
    room_visibility.drop(bind, checkfirst=True)
    dm_status.drop(bind, checkfirst=True)
    friend_request_status.drop(bind, checkfirst=True)
    conversation_type.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
